goog.declareModuleId('os.state.v4.LayerTag');

/**
 * XML tags for layer state
 * @enum {string}
 */
const LayerTag = {
  ANIMATE: 'animate',
  ARROW_SIZE: 'arrowSize',
  ARROW_UNITS: 'arrowUnits',
  BFS: 'basicFeatureStyle',
  COLOR: 'color',
  CONTRAST: 'contrast',
  CSV_COMMENT_CHAR: 'commentChar',
  CSV_HEADER_ROW: 'headerRow',
  CSV_DATA_ROW: 'dataRow',
  CSV_USE_HEADER: 'useHeader',
  DATA_PROVIDER: 'dataProvider',
  IS_BASE_LAYER: 'isBaseLayer',
  FILL_COLOR: 'fillColor',
  FILL_OPACITY: 'fillOpacity',
  LABEL_COLUMN: 'labelColumn',
  LABEL_COLUMNS: 'labelColumns',
  LABEL: 'label',
  LABEL_COLOR: 'labelColor',
  LABEL_SIZE: 'labelSize',
  LOB_COLUMN_LENGTH: 'lobColumnLength',
  LOB_LENGTH: 'lobLength',
  LOB_LENGTH_TYPE: 'lobLengthType',
  LOB_LENGTH_ERROR: 'lobLengthError',
  LOB_LENGTH_COLUMN: 'lobLengthColumn',
  LOB_LENGTH_UNITS: 'lobLengthUnits',
  LOB_LENGTH_ERROR_UNITS: 'lobLengthErrorUnits',
  LOB_LENGTH_ERROR_COLUMN: 'lobLengthErrorColumn',
  LOB_BEARING_COLUMN: 'lobBearingColumn',
  LOB_BEARING_ERROR: 'lobBearingError',
  LOB_BEARING_ERROR_COLUMN: 'lobBearingErrorColumn',
  ICON_STYLE: 'iconStyle',
  MAP_URL: 'getMapUrl',
  MAPPINGS: 'mappings',
  PARAMS: 'params',
  PARSER_CONFIG: 'parserConfig',
  PROVIDER_TYPE: 'provider',
  PT_COLOR: 'pointColor',
  PT_OPACITY: 'pointOpacity',
  PT_SIZE: 'pointSize',
  TITLE: 'title',
  SHOW_LABELS: 'showLabels',
  SHOW_ARROW: 'showArrow',
  SHOW_ELLIPSE: 'showEllipse',
  SHOW_ELLIPSOIDS: 'showEllipsoids',
  SHOW_ERROR: 'showError',
  SHOW_GROUND_REF: 'showGroundRef',
  SHOW_ROTATION: 'showRotation',
  ROTATION_COLUMN: 'rotationColumn',
  STYLES: 'styles',
  TAGS: 'tags',
  TIME_ENABLED: 'timeEnabled',
  USE_HEADER: 'useHeader',
  REFRESH_RATE: 'refreshRate',
  EXTENTS: 'extents',
  EXTENT: 'extent',
  OPACITY: 'opacity',
  ALPHA: 'alpha',
  BIN_SETTINGS: 'binSettings',
  BIN: 'bin',
  BIN_SIZE: 'binSize',
  BINS: 'bins',
  ACTIVE: 'active',
  BIN_FIELD: 'field',
  BIN_TYPE: 'type',
  BIN_WIDTH: 'width',
  BIN_OFFSET: 'offset',
  COLOR_MODEL: 'colorModel',
  COLOR_MODEL_METHOD: 'colorMethod',
  COLOR_MODEL_BIN_METHOD: 'binMethod',
  COLOR_MODEL_MANUAL_COLORS: 'manualColors',
  COLOR_MODEL_NAME: 'name',
  COLOR_MODEL_VALUE: 'value',
  COLOR_MODEL_PAIR: 'pair'
};

export default LayerTag;
