goog.module('os.Fields');
goog.module.declareLegacyNamespace();

/**
 * @enum {string}
 */
exports = {
  ALT: 'ALTITUDE',
  ALT_UNITS: 'ALTITUDE_UNITS',
  BEARING: 'BEARING',
  CONFIDENCE: 'CONFIDENCE',
  DESCRIPTION: 'DESCRIPTION',
  ENDOFFSET: 'ENDOFFSET',
  FILENAME: 'FILENAME',
  FUZZY: 'FUZZY',
  GEOM_ALT: 'GEOM_ALT',
  GEOMETRY: 'GEOMETRY',
  GEOTAG: 'GEOTAG',
  ID: 'ID',
  LAT: 'LAT',
  LAT_DDM: 'LAT_DDM',
  LAT_DMS: 'LAT_DMS',
  LON: 'LON',
  LON_DMS: 'LON_DMS',
  LON_DDM: 'LON_DDM',
  MGRS: 'MGRS',
  NAME: 'NAME',
  LOWERCASE_NAME: 'name',
  ORIENTATION: 'ORIENTATION',
  PROPERTIES: 'PROPERTIES',
  RADIUS: 'RADIUS',
  RADIUS_UNITS: 'RADIUS_UNITS',
  SEMI_MAJOR: 'SEMI_MAJOR',
  SEMI_MAJOR_UNITS: 'SEMI_MAJ_UNITS',
  SEMI_MINOR: 'SEMI_MINOR',
  SEMI_MINOR_UNITS: 'SEMI_MINOR_UNITS',
  STARTOFFSET: 'STARTOFFSET',
  TIME: 'TIME',
  URL: 'URL'
};
